### ISSUE TITLE
Build fails if any files are edited or removed.

### ISSUE THREAD

**Issue by Bonboon229** [froggestspirit/SDATTool#10]
Rebuilding SDAT will fail on any option if any files are removed or edited.

Exampe of failiure regarding removed files using Pokemon B2W2's Sdat:

C:\Users\Goji Goodra\Downloads\SDATEDIT>py SDATTool -b b2w2.sdat
Building...
Traceback (most recent call last):
  File "C:\Users\Goji Goodra\Downloads\SDATEDIT\SDATTool\__main__.py", line 391, in <module>
    main()
  File "C:\Users\Goji Goodra\Downloads\SDATEDIT\SDATTool\__main__.py", line 384, in main
    build(args)
  File "C:\Users\Goji Goodra\Downloads\SDATEDIT\SDATTool\__main__.py", line 325, in build
    build_fileBlock(sdat, args)
  File "C:\Users\Goji Goodra\Downloads\SDATEDIT\SDATTool\Sdat.py", line 574, in build_fileBlock
    write_sseq(read_sseq_from_midi(args, fName), args, fName)
  File "C:\Users\Goji Goodra\Downloads\SDATEDIT\SDATTool\Midi.py", line 301, in read_sseq_from_midi
    raise Exception(f"Missing File:{testPath}")
Exception: Missing File:b2w2/Files/SEQ/SEQ_PV001.mid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Goji Goodra\Downloads\SDATEDIT\SDATTool\__main__.py", line 393, in <module>
    raise Exception(e)
Exception: Missing File:b2w2/Files/SEQ/SEQ_PV001.mid

In this case, I had manually removed all non music related files. (SFX and the like, leaving music, musical effects and STRM alone)

**Comment by froggestspirit** [comment]
The files will also need to be removed from the text files that may reference them, like FileBlock.json and InfoBlock.json

Edit: actually, the recommended way to build without files, is to just remove them from the json files, since they control what gets included

**Comment by Bonboon229** [comment]
Sorry to reopen this, tried what you suggested, only made things worse

**Comment by froggestspirit** [comment]
What error are you receiving?

**Comment by Bonboon229** [comment]
Same as before.
Heck, even trying to optomize without ANY edits will cause the error

**Comment by Bonboon229** [comment]
Also the write raw option is broken

**Comment by froggestspirit** [comment]
It looks like youre missing the b2w2/Files/SEQ/SEQ_PV001.mid file

**Comment by Bonboon229** [comment]
If it helps, what I just did was take an unedited pokemon HGSS sdat, unpack it, then attempted rebuild without touching ANY files whist using the -o (Optimize) option.
Error is as follows.
C:\Users\Goji Goodra\Music\SDAT>python sdattool hgss.sdat -o -b
Building...
Traceback (most recent call last):
  File "sdattool\__main__.py", line 391, in <module>
    main()
  File "sdattool\__main__.py", line 384, in main
    build(args)
  File "sdattool\__main__.py", line 321, in build
    build_infoBlock(sdat)
  File "sdattool\Sdat.py", line 478, in build_infoBlock
    exec(f"sdat.infoBlock.write(sdat, sdat.infoBlock.{infoBlockGroup[i]}, ii)")
  File "<string>", line 1, in <module>
  File "sdattool\Sdat.py", line 82, in write
    type[index].write(sdat)
  File "sdattool\Sdat.py", line 120, in write
    append_short(sdat, sdat.names[FILE].index(self.fileName))
ValueError: 'SEQ_PV001.sseq' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sdattool\__main__.py", line 393, in <module>
    raise Exception(e)
Exception: 'SEQ_PV001.sseq' is not in list

Note: This sdat was totally untouched. no files removed prior to rebuilding with -o

**Comment by froggestspirit** [comment]
The folder youre building is named hgss right? Normally youll want to
include both the folder name and sdat name to be sure

**Comment by Bonboon229** [comment]
Lemme give it a try
brb

**Comment by Bonboon229** [comment]
Using the build option -b alone succeeds on unmodified folder
Using build option with any other option causes this same error
Building...
Traceback (most recent call last):
  File "sdattool\__main__.py", line 391, in <module>
    main()
  File "sdattool\__main__.py", line 384, in main
    build(args)
  File "sdattool\__main__.py", line 321, in build
    build_infoBlock(sdat)
  File "sdattool\Sdat.py", line 478, in build_infoBlock
    exec(f"sdat.infoBlock.write(sdat, sdat.infoBlock.{infoBlockGroup[i]}, ii)")
  File "<string>", line 1, in <module>
  File "sdattool\Sdat.py", line 82, in write
    type[index].write(sdat)
  File "sdattool\Sdat.py", line 120, in write
    append_short(sdat, sdat.names[FILE].index(self.fileName))
ValueError: 'SEQ_PV001.sseq' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sdattool\__main__.py", line 393, in <module>
    raise Exception(e)
Exception: 'SEQ_PV001.sseq' is not in list

**Comment by Bonboon229** [comment]
To be honest, this tool seems to barely work at all.
Kirby Super Star Ultra's SDAT fails to unpack with this error showing up
C:\Users\Goji Goodra\Music\SDAT>python sdattool kssu.sdat -u
Unpacking...
Traceback (most recent call last):
  File "sdattool\__main__.py", line 391, in <module>
    main()
  File "sdattool\__main__.py", line 382, in main
    unpack(args)
  File "sdattool\__main__.py", line 63, in unpack
    unpack_fileBlock(sdat, args)
  File "sdattool\Sdat.py", line 549, in unpack_fileBlock
    write_sseq_to_midi(read_sseq(sdat), args, tempName)
  File "sdattool\Midi.py", line 121, in write_sseq_to_midi
    seq.commands[i].binary += cmd.argument.to_bytes(1, "big")
OverflowError: int too big to convert

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sdattool\__main__.py", line 393, in <module>
    raise Exception(e)
Exception: int too big to convert

**Comment by Bonboon229** [comment]
And Kirby Squeak Squad just hangs on unpack with nothing appearing in an extracted folder

**Comment by froggestspirit** [comment]
I was getting the same error. I think a lot of things broke with the midi update. I still have that code in the dev branch, but for the time being, I rolled back to an earlier version, which should be more stable. I know it's not as optimal, but other tools can be used to edit SSEQ if needed, though this should allow the SDAT itself to be unpacked and rebuilt correctly.

**Comment by Bonboon229** [comment]
Better then nothing, I suppose

**Comment by froggestspirit** [comment]
Thinking about it more, you could use the dev branch without the optimize
options, then after any edits, optimize with the main branch

**Comment by Bonboon229** [comment]
I'll give it a try
Will report in a few

**Comment by Bonboon229** [comment]
Edit: Tried just doing a removal edit of all music related data with the White 2 Sdat.
All building options results in this.

Building...
Traceback (most recent call last):
  File "C:\Users\Goji Goodra\Downloads\TEMP\SDATTool\__main__.py", line 391, in <module>
    main()
  File "C:\Users\Goji Goodra\Downloads\TEMP\SDATTool\__main__.py", line 384, in main
    build(args)
  File "C:\Users\Goji Goodra\Downloads\TEMP\SDATTool\__main__.py", line 78, in build
    sdat.infoBlock.load(sdat, json.load(infile))
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 42812 column 6 (char 1126879)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Goji Goodra\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Goji Goodra\Downloads\TEMP\SDATTool\__main__.py", line 393, in <module>
    raise Exception(e)
Exception: Expecting ',' delimiter: line 42812 column 6 (char 1126879)
